version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/certs/localhost.crt:/etc/ssl/certs/server.crt
      - ~/certs/localhost.key:/etc/ssl/private/server.key
  web:
    image: httpd
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html
