version: '3.3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/certs/localhost/localhost.crt:/etc/ssl/certs/server.crt
      - ~/certs/localhost/localhost.key:/etc/ssl/private/server.key